# Generated by Django 5.1.1 on 2024-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusFlow', '0010_alter_profile_profile_picture_alter_profile_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
